In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_excel("Telco_customer_churn.xlsx")
# df

In [3]:
# df["Count"].nunique()

In [4]:
# df.info()

In [5]:
## CLTV - Customer Lifetime Value -- This gives the value about how long the customer was associated. 
## This may leak the data while testing

In [6]:
# df["Country"].value_counts()

In [7]:
# df["State"].value_counts()

In [8]:
# df.columns

In [9]:
drop_cols = ['CustomerID', 'Count', 'Country', 'State',
       'Lat Long', 'Latitude', 'Longitude',  'Churn Label', 
       'Churn Score', 'CLTV', 'Churn Reason']
df=df.drop(columns=drop_cols)

In [10]:
df.shape

(7043, 22)

In [11]:
df["Total Charges"]=pd.to_numeric(df["Total Charges"],errors="coerce")

In [12]:
# df.info()

In [13]:
### KNN imputer for missing values in Total Charges

In [14]:
from sklearn.impute import KNNImputer

In [15]:
knn_imputer=KNNImputer(n_neighbors=5)
df[["Total Charges"]]=knn_imputer.fit_transform(df[["Total Charges"]])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   City               7043 non-null   object 
 1   Zip Code           7043 non-null   int64  
 2   Gender             7043 non-null   object 
 3   Senior Citizen     7043 non-null   object 
 4   Partner            7043 non-null   object 
 5   Dependents         7043 non-null   object 
 6   Tenure Months      7043 non-null   int64  
 7   Phone Service      7043 non-null   object 
 8   Multiple Lines     7043 non-null   object 
 9   Internet Service   7043 non-null   object 
 10  Online Security    7043 non-null   object 
 11  Online Backup      7043 non-null   object 
 12  Device Protection  7043 non-null   object 
 13  Tech Support       7043 non-null   object 
 14  Streaming TV       7043 non-null   object 
 15  Streaming Movies   7043 non-null   object 
 16  Contract           7043 

In [17]:
### EDA
df.describe()

,Zip Code,Tenure Months,Monthly Charges,Total Charges,Churn Value
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,93521.964646,32.371149,64.761692,2283.300441,0.265370
std,1865.794555,24.559481,30.090047,2265.000258,0.441561
min,90001.000000,0.000000,18.250000,18.800000,0.000000
25%,92102.000000,9.000000,35.500000,402.225000,0.000000
50%,93552.000000,29.000000,70.350000,1400.550000,0.000000
75%,95351.000000,55.000000,89.850000,3786.600000,1.000000
max,96161.000000,72.000000,118.750000,8684.800000,1.000000


In [18]:
### from above mean and median are almost same that means the data is normally distributed and that too symmetric(std)

In [19]:
cat_cols=df.select_dtypes(include=["object","category"]).columns
for col in cat_cols:
    print(f"{col} : {df[col].nunique()}")

City : 1129
Gender : 2
Senior Citizen : 2
Partner : 2
Dependents : 2
Phone Service : 2
Multiple Lines : 3
Internet Service : 3
Online Security : 3
Online Backup : 3
Device Protection : 3
Tech Support : 3
Streaming TV : 3
Streaming Movies : 3
Contract : 3
Paperless Billing : 2
Payment Method : 4


In [20]:
### City - freq
### Binary - label/map function
### three and 4 classes - label 

In [21]:
freq=df["City"].value_counts()
df["City"]=df["City"].map(freq)

In [22]:
binary_col=["Gender",
"Senior Citizen",
"Partner",
"Dependents",
"Phone Service",
"Paperless Billing"]
for col in binary_col:
    print(df[col].value_counts())

Gender
Male      3555
Female    3488
Name: count, dtype: int64
Senior Citizen
No     5901
Yes    1142
Name: count, dtype: int64
Partner
No     3641
Yes    3402
Name: count, dtype: int64
Dependents
No     5416
Yes    1627
Name: count, dtype: int64
Phone Service
Yes    6361
No      682
Name: count, dtype: int64
Paperless Billing
Yes    4171
No     2872
Name: count, dtype: int64


In [23]:
binary_col=["Gender",
"Senior Citizen",
"Partner",
"Dependents",
"Phone Service",
"Paperless Billing"]
for col in binary_col:
    df[col]=df[col].map({"Yes":1,"No":0,"Male":1,"Female":0})
    df[col]=pd.to_numeric(df[col],errors="coerce")

In [24]:
df_2=df
df_3=df
df_4=df

## 1st Iteration

In [26]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
cat_cols=df.select_dtypes(include=["object","category"]).columns
for col in cat_cols:
    df[col]=le.fit_transform(df[col])

In [27]:
X=df.drop("Churn Value",axis=1)
y=df["Churn Value"]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   City               7043 non-null   int64  
 1   Zip Code           7043 non-null   int64  
 2   Gender             7043 non-null   int64  
 3   Senior Citizen     7043 non-null   int64  
 4   Partner            7043 non-null   int64  
 5   Dependents         7043 non-null   int64  
 6   Tenure Months      7043 non-null   int64  
 7   Phone Service      7043 non-null   int64  
 8   Multiple Lines     7043 non-null   int32  
 9   Internet Service   7043 non-null   int32  
 10  Online Security    7043 non-null   int32  
 11  Online Backup      7043 non-null   int32  
 12  Device Protection  7043 non-null   int32  
 13  Tech Support       7043 non-null   int32  
 14  Streaming TV       7043 non-null   int32  
 15  Streaming Movies   7043 non-null   int32  
 16  Contract           7043 

In [29]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [30]:
## Model building

In [31]:
## classification
# logistic_regression
# KNN
# SVM
# DT
# RandomForest
# StackingClassifer
# XGBoost
## Can try for all the classification models

In [32]:
## Simple Model-Logistic
## Bagging - RandomForest
## Boosting - XGBoost

In [33]:
### Scaling
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression()
lr_model.fit(X_train,y_train)

LogisticRegression()

In [34]:
from sklearn.ensemble import RandomForestClassifier

X=df_2.drop("Churn Value",axis=1)
y=df_2["Churn Value"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

rf_model=RandomForestClassifier()
rf_model.fit(X_train,y_train)

RandomForestClassifier()

In [35]:
from xgboost import XGBClassifier

xgb_model=XGBClassifier()
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [36]:
models={"LR":lr_model,"RF":rf_model,"XGB":xgb_model}

for name,model in models.items():
    y_pred=model.predict(X_test)
    print(name)
    print("Accuracy :",accuracy_score(y_test,y_pred))
    print("Confusion Matrix :")
    print(confusion_matrix(y_test,y_pred))
    print("Classification Report :",classification_report(y_test,y_pred))
    print("-"*50)

LR
Accuracy : 0.2654364797728886
Confusion Matrix :
[[   0 1035]
 [   0  374]]
Classification Report :               precision    recall  f1-score   support

           0       0.00      0.00      0.00      1035
           1       0.27      1.00      0.42       374

    accuracy                           0.27      1409
   macro avg       0.13      0.50      0.21      1409
weighted avg       0.07      0.27      0.11      1409

--------------------------------------------------
RF
Accuracy : 0.7927608232789212
Confusion Matrix :
[[929 106]
 [186 188]]
Classification Report :               precision    recall  f1-score   support

           0       0.83      0.90      0.86      1035
           1       0.64      0.50      0.56       374

    accuracy                           0.79      1409
   macro avg       0.74      0.70      0.71      1409
weighted avg       0.78      0.79      0.78      1409

--------------------------------------------------
XGB
Accuracy : 0.7750177430801988
Confusio

### 2nd Iteration

In [38]:
### SMOTE Technique

In [39]:
X=df.drop("Churn Value",axis=1)
y=df["Churn Value"]

In [40]:
from imblearn.combine import SMOTETomek

smt=SMOTETomek()
X,y=smt.fit_resample(X,y)

In [41]:
y.value_counts()

Churn Value
1    4743
0    4743
Name: count, dtype: int64

In [42]:
### Logistic Regresssion -- CV -- Best model
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [44]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
param_lr={"C":[0.001,0.01,0.1,1,10,100],
         "penalty":["l2"],
         "solver":["lbfgs"]}

grid_lr=GridSearchCV(LogisticRegression(max_iter=1000,class_weight='balanced'),
                     param_grid=param_lr,
                     scoring="accuracy",
                     n_jobs=-1)
grid_lr.fit(X_train,y_train)
best_lr=grid_lr.best_estimator_
print("Best LR Model",grid_lr.best_params_)

Best LR Model {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}


In [46]:
### Random Forest -- CV -- Best model
X=df.drop("Churn Value",axis=1)
y=df["Churn Value"]

X,y=smt.fit_resample(X,y)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [48]:
param_rf={"n_estimators":[100,200,300,400,500],
         "max_depth":[3,4,5,6,7],
         "min_samples_split":[2,5,7,9,10],
        "min_samples_leaf":[1,2,3,4,5]}

random_rf=RandomizedSearchCV(RandomForestClassifier(class_weight='balanced'),
                     param_distributions=param_rf,
                     scoring="accuracy",
                     n_jobs=-1)
random_rf.fit(X_train,y_train)
best_rf=random_rf.best_estimator_
print("Best RF Model",random_rf.best_params_)

Best RF Model {'n_estimators': 400, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_depth': 7}


In [49]:
### XGBoost -- CV -- Best model
param_xgb={"n_estimators":[200,300,400,500],
         "max_depth":[3,4,5,6,7],
         "learning_rate":[0.01,0.03,0.05,0.1],
        "sub_sample":[0.7,0.8,0.9,1],
        "gamma":[0,0.1,0.2,0.3],
          "min_child_weight":[1,3,5]}
scale_pos_weight=(y_train==0).sum()/(y_train==1).sum() ## Uses to check the balance of data

random_xgb=RandomizedSearchCV(XGBClassifier(
    eval_metric="logloss"),
    param_distributions=param_xgb,
    scoring="accuracy",
    n_jobs=-1,
    random_state=42)
random_xgb.fit(X_train,y_train)
best_xgb=random_xgb.best_estimator_
print("Best XGB Model",random_xgb.best_params_)

Best XGB Model {'sub_sample': 0.9, 'n_estimators': 300, 'min_child_weight': 1, 'max_depth': 7, 'learning_rate': 0.05, 'gamma': 0.1}


In [50]:
### We have best parameters for all models
## Performance-- 

In [51]:
models={"LR":best_lr,"RF":best_rf,"XGB":best_xgb}

for name,model in models.items():
    y_pred=model.predict(X_test)
    print(name)
    print("Accuracy :",accuracy_score(y_test,y_pred))
    print("Confusion Matrix :")
    print(confusion_matrix(y_test,y_pred))
    print("Classification Report :",classification_report(y_test,y_pred))
    print("-"*50)

LR
Accuracy : 0.3771186440677966
Confusion Matrix :
[[434 505]
 [671 278]]
Classification Report :               precision    recall  f1-score   support

           0       0.39      0.46      0.42       939
           1       0.36      0.29      0.32       949

    accuracy                           0.38      1888
   macro avg       0.37      0.38      0.37      1888
weighted avg       0.37      0.38      0.37      1888

--------------------------------------------------
RF
Accuracy : 0.8485169491525424
Confusion Matrix :
[[751 188]
 [ 98 851]]
Classification Report :               precision    recall  f1-score   support

           0       0.88      0.80      0.84       939
           1       0.82      0.90      0.86       949

    accuracy                           0.85      1888
   macro avg       0.85      0.85      0.85      1888
weighted avg       0.85      0.85      0.85      1888

--------------------------------------------------
XGB
Accuracy : 0.8734110169491526
Confusion Ma